# ╔════════════════════════════════════════════════════════════════════════════╗
# ║  cmake/KairosInstall.cmake — Install rules                              ║
# ║  Spec reference: §28.10                                                 ║
# ╚════════════════════════════════════════════════════════════════════════════╝

include(GNUInstallDirs)

# ── Binary ─────────────────────────────────────────────────────────────────
install(TARGETS kairos
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)

# ── Headers (for library API users) ───────────────────────────────────────
install(DIRECTORY include/kairos
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
    FILES_MATCHING PATTERN "*.hpp"
)

# ── Example config ─────────────────────────────────────────────────────────
install(FILES deploy/kairos.toml.example
    DESTINATION ${CMAKE_INSTALL_DATADIR}/kairos
)

# ── Service files (platform-specific) ─────────────────────────────────────
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    install(FILES deploy/systemd/kairos.service
        DESTINATION ${CMAKE_INSTALL_PREFIX}/lib/systemd/system
    )
endif()

# ── Shell completions ─────────────────────────────────────────────────────
# These are generated by `kairos completions {bash,zsh,fish}` and placed
# in deploy/completions/ at build time.  The install target copies them to
# the standard completion directories.
#
# Users can also generate them dynamically:
#   eval "$(kairos completions bash)"
#   eval "$(kairos completions zsh)"
#   kairos completions fish | source

if(EXISTS "${CMAKE_SOURCE_DIR}/deploy/completions/kairos.bash")
    install(FILES deploy/completions/kairos.bash
        DESTINATION ${CMAKE_INSTALL_DATADIR}/bash-completion/completions
        RENAME kairos
    )
endif()

if(EXISTS "${CMAKE_SOURCE_DIR}/deploy/completions/kairos.zsh")
    install(FILES deploy/completions/kairos.zsh
        DESTINATION ${CMAKE_INSTALL_DATADIR}/zsh/site-functions
        RENAME _kairos
    )
endif()

if(EXISTS "${CMAKE_SOURCE_DIR}/deploy/completions/kairos.fish")
    install(FILES deploy/completions/kairos.fish
        DESTINATION ${CMAKE_INSTALL_DATADIR}/fish/vendor_completions.d
        RENAME kairos.fish
    )
endif()
